# Generated by Django 4.1.3 on 2023-03-03 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_record', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales_record',
            name='bought_by',
        ),
    ]
